#########################################################################################
'''
The code in this file generates scatter plots of P vs F for different zones and scales. 
It reads CSV files from directories matching the pattern "var_lfxx" and creates a subplot 
for each zone, plotting the data points with different markers and colors for each scale. 
The resulting figure includes a legend and is displayed using Matplotlib.

Code generated by ChatGPT.
'''
#########################################################################################

import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


base_dir = Path(__file__).resolve().parent
zones = ["zone1", "zone2", "zone3"]
scale_pattern = re.compile(r"^var_lf\d+$")

scale_dirs = sorted(
    [p for p in base_dir.iterdir() if p.is_dir() and scale_pattern.match(p.name)]
)

if not scale_dirs:
    raise FileNotFoundError("No var_lfxx folders found in the workspace root.")

fig, axes = plt.subplots(1, len(zones), figsize=(18, 5), sharey=True)
axes = np.atleast_1d(axes)

markers = ["o", "s", "^", "D", "P", "X", "*", ">", "<", "v"]
colors = plt.cm.tab10(np.linspace(0, 1, len(scale_dirs)))

for ax, zone in zip(axes, zones):
    for idx, scale_dir in enumerate(scale_dirs):
        csv_path = scale_dir / zone / "output.csv"
        if not csv_path.exists():
            continue

        df = pd.read_csv(csv_path)
        if {"P", "F"}.issubset(df.columns):
            x = df["P"].to_numpy()
            y = df["F"].to_numpy()
            ax.scatter(
                x,
                y,
                s=40,
                marker=markers[idx % len(markers)],
                color=colors[idx],
                alpha=0.7,
                label=scale_dir.name,
            )

    ax.set_title(zone)
    ax.set_xlabel("P")
    ax.set_ylabel("F")
    ax.grid(True, alpha=0.3)

handles, labels = axes[0].get_legend_handles_labels()
fig.legend(handles, labels, loc="upper center", ncol=min(4, len(labels)), frameon=False)
fig.suptitle("Scatter Plot of P vs F by Zone and Scale")
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()
